name: lemonsh
description: A simple package manager and shell in Dart
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.1
  archive: ^3.6.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  
